language: scala

scala:
  - 2.12.8

services:
  - docker

script:
  - sbt clean compile

deploy:
  skip_cleanup: true
  provider: script
  script: bash push_docker.sh
  on:
    branch: master












