language: scala

scala:
  - 2.12.8

script:
  - sbt clean compile

after_success:
  - sbt assembly
  - docker build -t catan ./
  - docker push gherman27/catan-ml:catan
  on:
    branch: master












