language: scala

services:
  - docker

scala:
  - 2.12.8

script:
  - sbt clean compile


  script:
    - sbt assembly
    - docker build -t catan ./
    - docker push gherman27/catan-ml:catan
    on:
      branch: master



